### ISSUE TITLE
Can't safely use nvg when mixed with other drawing

### ISSUE THREAD

**Issue by nokola** [sunli829/nvg#3]
First of all, awesome port and I really like the pure rust all the effort that went into this nvg port! Kudos!

Maybe I'm missing something, but here's the scenario I tried and can't get working unless I use unsafe:
1. I have class that manages an openGL device and implements `nvg::Renderer`, e.g.
```rust
let device = MyRenderer::new(...); // MyRenderer is imlp nvg::Renderer
let mut nvg_context = nvg::Context::create(device)?;
```
Now at some point I'd like to do something like this in frame drawing code:
```rust
fn update() {
        // draw the world
        device.draw_spinning_cube(); // example; won't work since I have no access to device.
        // some nvg code: draw some UI on top
        let origin = (150.0, 140.0);
        nvg_context.begin_path();
        nvg_context.circle(origin, 64.0);
        nvg_context.move_to(origin);
        nvg_context.line_to((origin.0 + 300.0, origin.1 - 50.0));
        nvg_context.stroke_paint(nvg::Color::rgba(1.0, 1.0, 0.0, 1.0));
        nvg_context.stroke_width(3.0);
        nvg_context.stroke().unwrap();
 ... etc.
}
```

The problem is that `nvg::Context::create()` owns ("eats") the `device` and I have no access to `device` anymore. To resolve it, I use this unsafe and static variable workaround:

```rust
static mut MY_DEVICE_CONTEXT: Option<DeviceContext > = None;
fn get_context() -> &'static mut DeviceContext {
    unsafe { MY_DEVICE_CONTEXT.as_mut().unwrap_or_else(|| panic!()) }
}
...
        unsafe { MY_DEVICE_CONTEXT= Some(MyDeviceContext::new(...)) };
        let device = MyRenderer::new(get_context()); // MyRenderer is imlp nvg::Renderer
        let mut nvg_context = nvg::Context::create(device)?;
...

// now I can call get_context() to access the device and nvg_context to draw the UI. But the workaround is quite unsightly
```

Ideally, nvg::Context::create would take `&renderer` borrow and when drawing a frame nvg_context would also take a temporary `&mut Renderer`.
Second option is to have a fn on nvg::Context that transfers ownership of `device` temporarily for using it in a caller and then retuning it back to nvg::Context.

I'll look more in the source to see if there's an easy way to do something like the above. If anyone has any suggestions, please let me know!

**Comment by sunli829** [comment]
Can you wrap your device in Arc?

**Comment by nokola** [comment]
Will try, thanks for the suggestion!

**Comment by nokola** [comment]
Just thinking - if I use Arc, then the checks for safety will be done at runtime, not compile time. Isn't it better to have the checks done at compile time by passing &device at the time of drawing? Then no need for Arc, etc.
I looked at the Render trait and I see that create_texture() and flush() are likely going to use the device. However not sure if/how nvg can be reworked (or if a good idea) to allow something like this:
```
    device.draw_stuff();
    nvg.stroke();
    nvg....
    nvg.flush(&device);
```
I'll think about it some more, because I'd rather not use Arc unless really needed.

**Comment by sunli829** [comment]
I don't think Arc is about security checks, it's just a way to share data.

**Comment by nokola** [comment]
Thanks for the info, will look into it some more.
