### ISSUE TITLE
Can't Transform Text

### ISSUE THREAD

**Issue by geom3trik** [sunli829/nvg#4]
It doesn't appear to be possible to transform text like you can with other paths. For example, I cannot rotate text using the rotate function in context. I've only glanced at the code, but it appears to be because the text rendering doesn't go through the same command list appedning as other path rendering which bypasses any transformations.

Would it be possible to add this feature? Ideally it would be good to be able to rotate an entire text string and not individual glyphs.

**Comment by sunli829** [comment]
Released `v0.5.10`

**Comment by geom3trik** [comment]
> Released `v0.5.10`

Yep that's fixed it! Closing issue.
