### ISSUE TITLE
Shape Antialias Causes Incorrect Stroke Width and Color For Odd Widths

### ISSUE THREAD

**Issue by geom3trik** [sunli829/nvg#5]
Forgive me if this is me not using the library correctly, but I've noticed that the stroke width and colour doesn't seem to match what I specify when the stroke width is set to an odd number when shape antialiasing is set to true. For example, if I set the stroke colour to black and width to 1.0 I end up with a 2px wide gray border as shown here:

![image](https://user-images.githubusercontent.com/9365407/86014985-ec9e4c00-ba18-11ea-9219-6f76baafab7a.png)

Inspecting the color of the stroke shows that it is a gray rather than black. Similarly if I change only the stroke color to red, rgb(1.0, 0.0, 0.0), but keep everything else the same I get this:

![image](https://user-images.githubusercontent.com/9365407/86015292-49016b80-ba19-11ea-8ab7-092e44c01b68.png)

Which is also 2px wide and not the correct color. Now if I set the stroke width to 2.0 I get what I would expect, a 2 pixels wide border with the specified color:

![image](https://user-images.githubusercontent.com/9365407/86015744-dba20a80-ba19-11ea-954b-f1ccf17a4af5.png)

Now if I try a stroke width of 3.0 I get this:

![image](https://user-images.githubusercontent.com/9365407/86016533-caa5c900-ba1a-11ea-83f5-20ec27995659.png)

It's difficult to see from the screenshot but the border is 4 pixels wide with a 2px wide black center surrounded by 1 pixel wide gray borders.

My DPI scaling is set to 1.0 so I assume that the units correspond directly to pixels. If I turn shape antialiasing off then the stroke width and color are exactly what I would expect except now I can't use rounded corners because they look terrible. I don't know how the antialiasing works but I'm assuming it is adding fragments to blend the edges and that could maybe be the cause?

I just want to say this is a great library by the way. Very easy to use and renders very quickly. Thank you for your time and effort.

**Comment by sunli829** [comment]
I fixed stroke width problem at `v0.5.11`.
